name = "Nerdacious Hobbies"
description = ""
keywords = ""
image = "logo.jpg"
theme = "dark"
primary_color = "#d81b60"
text_align = "center"
gtag_id = ""
base_url = "https://renrut5.github.io/nerdacious"

[[sections]]
title = "Follow on Social"
description = ""
direction = "row"
item_style = "filled"
icon_size = "20px"
[[sections.items]]
icon = "https://cdn.simpleicons.org/instagram/ffffff"
title = "Instagram"
url = "https://www.instagram.com/nerdacioushobbies"
[[sections.items]]
icon = "https://cdn.simpleicons.org/facebook/ffffff"
title = "Facebook"
url = "https://www.facebook.com/nerdacioushobbies"

[[sections]]
direction = "column"
item_style = "outline"
[[sections.items]]
title = "Etsy Shop"
description = ""
url = "#"

[[sections]]
title = "Payment Portals"
description = ""
direction = "column"
item_style = "outline"
[[sections.items]]
title = "PayPal"
icon = "https://cdn.simpleicons.org/paypal/ffffff"
url = "#"
[[sections.items]]
title = "Venmo"
icon = "https://cdn.simpleicons.org/venmo/ffffff"
url = "#"
[[sections.items]]
title = "Cash App"
icon = "https://cdn.simpleicons.org/cashapp/ffffff"
url = "#"
